"""generates tests from specs"""
"""
Task 3.4 / 4 / 5: Generate test cases for all three pipelines
  - tests/tests_manual.json   (template + validator)
  - tests/tests_auto.json     (generated by Groq LLM from spec_auto.md)
  - tests/tests_hybrid.json   (generated by Groq LLM from spec_hybrid.md)
"""

import json
import os
import re
import time

try:
    from groq import Groq
except ImportError:
    os.system("pip install groq")
    from groq import Groq

GROQ_API_KEY  = "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"
MODEL         = "meta-llama/llama-4-scout-17b-16e-instruct"
MAX_RETRIES   = 3

SPEC_MANUAL   = os.path.join("spec", "spec_manual.md")
SPEC_AUTO     = os.path.join("spec", "spec_auto.md")
SPEC_HYBRID   = os.path.join("spec", "spec_hybrid.md")

TESTS_MANUAL  = os.path.join("tests", "tests_manual.json")
TESTS_AUTO    = os.path.join("tests", "tests_auto.json")
TESTS_HYBRID  = os.path.join("tests", "tests_hybrid.json")

os.makedirs("tests", exist_ok=True)

TABLE_REQ_RE = re.compile(
    r"^\|\s*(REQ-\d+)\s*\|\s*([^|]+)\|\s*([^|]+)\|\s*(.*?)\s*\|\s*([^|]+)\|$"
)
SECTION_PERSONA_RE = re.compile(r"^##\s+Requirements\s+from\s+(.+?)\s+[—-]\s+(.+)$")


# ─────────────────────────────────────────────
#  Helpers
# ─────────────────────────────────────────────

def call_groq(client, prompt, temperature=0.3, max_tokens=2048):
    for attempt in range(MAX_RETRIES):
        try:
            response = client.chat.completions.create(
                model=MODEL,
                messages=[{"role": "user", "content": prompt}],
                temperature=temperature,
                max_tokens=max_tokens,
            )
            return response.choices[0].message.content
        except Exception as e:
            wait = 2 ** attempt
            print(f"  ⚠️  Groq error (attempt {attempt+1}/{MAX_RETRIES}): {e}")
            if attempt < MAX_RETRIES - 1:
                time.sleep(wait)
    return None


def extract_json_block(text):
    """Return the first JSON object or array found in a string."""
    # Try object first
    match = re.search(r"\{[\s\S]*\}", text)
    if match:
        try:
            return json.loads(match.group())
        except json.JSONDecodeError:
            pass
    # Try array
    match = re.search(r"\[[\s\S]*\]", text)
    if match:
        try:
            return json.loads(match.group())
        except json.JSONDecodeError:
            pass
    return None


def parse_requirements_from_spec(spec_path):
    """Parse requirement blocks from a spec .md file."""
    if not os.path.exists(spec_path):
        return []

    with open(spec_path, "r", encoding="utf-8") as f:
        content = f.read()

    reqs = []
    # Split on separator lines
    blocks = re.split(r"─{10,}", content)
    for block in blocks:
        rid_match     = re.search(r"Requirement ID:\s*(.+)", block)
        desc_match    = re.search(r"Description:\s*\[(.+?)\]", block, re.DOTALL)
        ac_match      = re.search(r"Acceptance Criteria:\s*\[(.+?)\]", block, re.DOTALL)
        persona_match = re.search(r"Source Persona:\s*\[(.+?)\]", block)
        notes_match   = re.search(r"Notes:\s*\[(.+?)\]", block, re.DOTALL)

        if rid_match:
            reqs.append({
                "id":          rid_match.group(1).strip(),
                "description": desc_match.group(1).strip()   if desc_match    else "",
                "acceptance":  ac_match.group(1).strip()     if ac_match      else "",
                "persona":     persona_match.group(1).strip() if persona_match else "",
                "notes":       notes_match.group(1).strip()  if notes_match   else "",
            })

    if reqs:
        return reqs

    current_persona = ""
    for line in content.splitlines():
        stripped = line.strip()
        section_match = SECTION_PERSONA_RE.match(stripped)
        if section_match:
            current_persona = section_match.group(2).strip()
            continue

        table_match = TABLE_REQ_RE.match(stripped)
        if not table_match:
            continue

        requirement_id, requirement_type, priority, description, derived_from = table_match.groups()
        if requirement_id == "Req ID":
            continue
        if set(requirement_id) == {"-"}:
            continue

        reqs.append({
            "id": requirement_id.strip(),
            "description": description.strip(),
            "acceptance": "",
            "persona": current_persona,
            "notes": f"{requirement_type.strip()} | {priority.strip()} | {derived_from.strip()}",
        })

    return reqs


def save_tests(tests, path):
    with open(path, "w", encoding="utf-8") as f:
        json.dump({"tests": tests}, f, indent=2)
    print(f"  ✅  Tests saved → {path}  ({len(tests)} test case(s))")


def validate_tests(tests, label, valid_requirement_ids=None):
    errors = []
    seen_ids = set()
    for t in tests:
        tid = t.get("test_id", "?")
        if not t.get("test_id"):
            errors.append("missing test_id")
        elif tid in seen_ids:
            errors.append(f"{tid}: duplicate test_id")
        else:
            seen_ids.add(tid)

        if not t.get("requirement_id"):
            errors.append(f"{tid}: missing requirement_id")
        elif valid_requirement_ids is not None and t.get("requirement_id") not in valid_requirement_ids:
            errors.append(f"{tid}: requirement_id '{t.get('requirement_id')}' not found in spec")
        if not t.get("scenario"):
            errors.append(f"{tid}: missing scenario")
        elif not isinstance(t.get("scenario"), str):
            errors.append(f"{tid}: scenario must be a string")

        steps = t.get("steps", [])
        if not isinstance(steps, list):
            errors.append(f"{tid}: steps must be a list")
        elif len(steps) < 2:
            errors.append(f"{tid}: fewer than 2 steps")
        elif any(not isinstance(step, str) or not step.strip() for step in steps):
            errors.append(f"{tid}: steps must contain non-empty strings")

        if not t.get("expected_result"):
            errors.append(f"{tid}: missing expected_result")
        elif not isinstance(t.get("expected_result"), str):
            errors.append(f"{tid}: expected_result must be a string")

    if errors:
        print(f"  ⚠️  [{label}] {len(errors)} issue(s):")
        for e in errors:
            print(f"       - {e}")
    else:
        print(f"  ✅  [{label}] All {len(tests)} tests valid.")
    return errors


def build_fallback_test(req, test_id, include_notes=False):
    scenario = req["description"].replace("The system shall ", "", 1).strip()
    if not scenario:
        scenario = f"Validate requirement {req['id']}"
    test = {
        "test_id": test_id,
        "requirement_id": req["id"],
        "scenario": scenario[:120],
        "steps": [
            f"Review the requirement context for {req['id']}.",
            "Perform the user action or system condition described by the requirement.",
            "Observe the system behavior and record the outcome.",
        ],
        "expected_result": req["acceptance"] or req["description"],
    }
    if include_notes:
        test["notes"] = "Generated from the current requirement text because no valid stored test matched the spec."
    return test


# ─────────────────────────────────────────────
#  MANUAL tests
# ─────────────────────────────────────────────

def handle_manual_tests():
    print("\n[MANUAL] Checking tests_manual.json …")

    if os.path.exists(TESTS_MANUAL):
        with open(TESTS_MANUAL, "r", encoding="utf-8") as f:
            data = json.load(f)
        tests = data.get("tests", [])
        print(f"  Found {len(tests)} existing manual test(s).")
        validate_tests(tests, "manual")
        return

    # Build a starter template from manual spec
    reqs = parse_requirements_from_spec(SPEC_MANUAL)
    if not reqs:
        reqs = [{
            "id": "FR1",
            "description": "PLACEHOLDER requirement description",
            "acceptance":  "PLACEHOLDER acceptance criteria",
            "persona":     "PLACEHOLDER persona",
            "notes":       "",
        }]

    tests = []
    for i, req in enumerate(reqs, start=1):
        tests.append({
            "test_id":        f"T_manual_{i}",
            "requirement_id": req["id"],
            "scenario":       f"PLACEHOLDER: Describe the test scenario for {req['id']}",
            "steps": [
                "PLACEHOLDER: Step 1 — describe the precondition / setup",
                "PLACEHOLDER: Step 2 — describe the user action",
                "PLACEHOLDER: Step 3 — describe what to verify",
            ],
            "expected_result": (
                f"PLACEHOLDER: {req['acceptance'][:120]}"
                if req["acceptance"] else "PLACEHOLDER: Expected outcome"
            ),
        })

    save_tests(tests, TESTS_MANUAL)
    print("  ✏️   Edit tests_manual.json to replace all PLACEHOLDER values.")


# ─────────────────────────────────────────────
#  LLM-based test generation (auto + hybrid)
# ─────────────────────────────────────────────

def generate_tests_with_llm(client, spec_path, prefix,
                             pipeline_label, output_path,
                             include_notes=False):
    print(f"\n[{pipeline_label.upper()}] Generating {os.path.basename(output_path)} …")

    reqs = parse_requirements_from_spec(spec_path)
    valid_requirement_ids = {req["id"] for req in reqs}

    if not reqs:
        print(f"  ERROR: No requirements parsed from {spec_path}. "
              f"Run 06_spec_generate.py first.")
        return

    if os.path.exists(output_path):
        print(f"  File already exists — skipping LLM generation.")
        with open(output_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        errors = validate_tests(data.get("tests", []), pipeline_label, valid_requirement_ids)
        if not errors:
            return
        print("  Regenerating file to match the current spec and required test format.")

    all_tests = []

    for i, req in enumerate(reqs, start=1):
        test_id = f"T_{prefix}_{i}"
        notes_instruction = (
            "Also include a 'notes' field (one sentence explaining what was "
            "refined or why this test was written this way)."
            if include_notes else
            "Do NOT include a 'notes' field."
        )

        prompt = f"""You are a QA engineer writing a structured test case for the
Headspace meditation app.

Requirement ID : {req['id']}
Description    : {req['description']}
Acceptance     : {req['acceptance']}
Source Persona : {req['persona']}

Write ONE test case for this requirement.
{notes_instruction}

Return ONLY valid JSON — no markdown fences, no explanation.

Use this exact schema:
{{
  "test_id": "{test_id}",
  "requirement_id": "{req['id']}",
  "scenario": "<short descriptive scenario name>",
  "steps": [
    "<step 1>",
    "<step 2>",
    "<step 3>"
  ],
  "expected_result": "<measurable expected result aligned with the acceptance criteria>"
  {', "notes": "<refinement note>"' if include_notes else ''}
}}"""

        raw = call_groq(client, prompt, temperature=0.2, max_tokens=700)
        if not raw:
            print(f"  ERROR: No response for {test_id}.")
            continue

        test = extract_json_block(raw)
        if not test:
            print(f"  ERROR: Could not parse JSON for {test_id}.")
            print(f"  Raw (first 300 chars): {raw[:300]}")
            test = build_fallback_test(req, test_id, include_notes)

        # Enforce required keys
        test.setdefault("test_id", test_id)
        test.setdefault("requirement_id", req["id"])
        test.setdefault("scenario", req["description"][:120] if req["description"] else f"Test for {req['id']}")
        test.setdefault("steps", ["Open the app", "Perform the action", "Verify the result"])
        test.setdefault("expected_result", req["acceptance"][:200] if req["acceptance"] else req["description"][:200])

        test["test_id"] = str(test["test_id"])
        test["requirement_id"] = req["id"]
        test["scenario"] = str(test["scenario"]).strip()
        if not isinstance(test.get("steps"), list):
            test["steps"] = [str(test.get("steps"))]
        test["steps"] = [str(step).strip() for step in test["steps"] if str(step).strip()]
        if len(test["steps"]) < 2:
            test["steps"] = build_fallback_test(req, test_id, include_notes)["steps"]
        test["expected_result"] = str(test["expected_result"]).strip()
        if include_notes and not test.get("notes"):
            test["notes"] = "Generated to satisfy the required test scenario format."

        all_tests.append(test)
        time.sleep(0.4)   # polite pacing

    if all_tests:
        save_tests(all_tests, output_path)
        validate_tests(all_tests, pipeline_label, valid_requirement_ids)
    else:
        print(f"  ERROR: No tests generated for {pipeline_label}.")


# ─────────────────────────────────────────────
#  MAIN
# ─────────────────────────────────────────────

def main():
    print("=" * 60)
    print("TEST GENERATION  —  07_tests_generate.py")
    print("=" * 60)

    client = Groq(api_key=GROQ_API_KEY)

    # Manual
    handle_manual_tests()

    # Automated
    generate_tests_with_llm(
        client,
        spec_path      = SPEC_AUTO,
        prefix         = "auto",
        pipeline_label = "auto",
        output_path    = TESTS_AUTO,
        include_notes  = False,
    )

    # Hybrid
    generate_tests_with_llm(
        client,
        spec_path      = SPEC_HYBRID,
        prefix         = "hybrid",
        pipeline_label = "hybrid",
        output_path    = TESTS_HYBRID,
        include_notes  = True,
    )

    print("\nAll test files processed.")


if __name__ == "__main__":
    main()
